# -*- coding: utf-8 -*-
"""初始化映射

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DrSaB8yAAbM76BCaYWquBi2WBHs-jKv
"""

# -*- coding: utf-8 -*-
"""ComfyUI Node Init

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdqWKP2x7gkH2rT0q5mSW2NAHLpeqhaQ
"""

from .gemini_node import GeminiMattingNode

NODE_CLASS_MAPPINGS = {
    "GeminiMattingNode": GeminiMattingNode
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "GeminiMattingNode": "Gemini AI Matting (Pro)"
}

# 这一行非常重要：告诉 ComfyUI 加载当前目录下的 'js' 文件夹作为前端扩展
WEB_DIRECTORY = "./js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']