# -*- coding: utf-8 -*-
"""ComfyUI Node Init

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdqWKP2x7gkH2rT0q5mSW2NAHLpeqhaQ
"""

from .gemini_node import GeminiMattingNode

NODE_CLASS_MAPPINGS = {
    "GeminiMattingNode": GeminiMattingNode
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "GeminiMattingNode": "Gemini AI Matting (Pro)"
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']